### ISSUE TITLE
PUBLISHER_KEY

### ISSUE THREAD

**Issue by crownclown90** [Heyzap/heyzap-cordova#13]
What is a PUBLISHER_KEY?
in the dash board there is a "Publisher ID"  and a "API Key" which should be used if either, or where can the PUBLISHER_KEY be found ?

i have tried both in either, i am still unable to view ads
when calling  HeyzapAds.showMediationTestSuite(); i get the window and it only says searching for third party network adapters

**Comment by vintage** [comment]
https://github.com/Heyzap/heyzap-cordova/issues/12

**Comment by ekilah** [comment]
Should be your Publisher ID.
