### ISSUE TITLE
Security vulnerabilities in heyzap plugins reported by Google Play

### ISSUE THREAD

**Issue by rafaellop** [Heyzap/heyzap-cordova#23]
I've uploaded my APK with the following plugins included:

```
heyzap-cordova 1.2.1 "Heyzap"
heyzap-cordova-admob 1.0.1 
heyzap-cordova-applovin 1.0.3 
heyzap-cordova-facebook_audience_network 1.0.2 
```

and the Google Play reports security vulnerabilities in my app:

```
Sending Advertising ID Detected in APK 10000
Your app is sending Advertising ID over an unencrypted connection.

This isn't recommended because network intermediaries might be able to intercept it. You should use an encrypted connection when sending Advertising ID.
```

I suppose the same issue will come up on iOS. How to make the Heyzap plugins use secure channel for sending Advertising ID?

**Comment by rafaellop** [comment]
The extra packages don't change anything. It's enough to only use the `heyzap-cordova` to get the security warning in Google Play.  Any help?

**Comment by ezpuzz** [comment]
We are working on it for the next SDK release.

**Comment by rafaellop** [comment]
@ezpuzz HEYZAP! Do something about that or make the sources open so that I could fix this on my own!

```
Sending Advertising ID Detected in APK 11000, 10400, 10301, 10300
Your app is sending Advertising ID over an unencrypted connection.

This isn't recommended because network intermediaries might be able to intercept it. You should use an encrypted connection when sending Advertising ID.
```

**Comment by rafaellop** [comment]
Fixed?

**Comment by ekilah** [comment]
Yes, this was resolved in our Android SDK a while back, you shouldn't experience this issue anymore.
