### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hassankhan** [Heyzap/heyzap-cordova#3]
Hi, can you release a new version of the plugin? The latest available on `npm` is 1.1.3, it looks like a recent commit bumped it to 1.1.5.

I want to test if the `heyzap-extras` repo works with the latest version since I'm not having any luck at the moment.

**Comment by hassankhan** [comment]
+1?

**Comment by vintage** [comment]
I think it has been already fixed, as the latest version on the npm https://www.npmjs.com/package/heyzap-cordova is 1.2.1

Can it be closed now?

**Comment by hassankhan** [comment]
Yeah think so 👍
