### ISSUE TITLE
Not updating to 9.15.1 on iOS

### ISSUE THREAD

**Issue by rafaellop** [Heyzap/heyzap-cordova#34]
1) cordova plugin rm heyzap-cordova
2) cordova plugin add heyzap-cordova

The `HeyzapAds.h in the KeyzapAds.framework/Headers shows is still:
`#define SDK_VERSION @"9.14.1"

**Comment by ekilah** [comment]
Updated this morning on npm

**Comment by rafaellop** [comment]
I've been referring to the updated version. Tested today.

**Comment by ekilah** [comment]
https://github.com/Heyzap/heyzap-cordova/blob/master/src/ios/sdk/Heyzap/HeyzapAds.framework/Versions/A/Headers/HeyzapAds.h#L64

You submitted this 13 hours ago, NPM was updated after you submitted this.

**Comment by rafaellop** [comment]
Sorry, it must be the time difference between our locations.
