### ISSUE TITLE
Displaying ads doesn't work

### ISSUE THREAD

**Issue by vintage** [Heyzap/heyzap-cordova#8]
Here is my code. Instead of `xxx` I'm using Publisher ID found at https://developers.heyzap.com/account

```
HeyzapAds.start("xxx").then(function() {

      return HeyzapAds.showMediationTestSuite(); // returns a Promise

    }, function(error) {
      console.log("********");
      console.log(error);
      console.log("********");
    });
```

and here is the output:

```
2016-10-29 20:50:23.633062 Quiz for HoN[2741:902025] FYBHZMediationTestSuite - showFromViewController: <MainViewController: 0x11dd0c2f0>
2016-10-29 20:50:23.633263 Quiz for HoN[2741:902025] FYBHZMediationTestSuite - note: showing before the Fyber SDK is initalized.
2016-10-29 20:50:23.733064 Quiz for HoN[2741:902025] [FYB Debug]: App Transport Security: {
    NSAllowsArbitraryLoads = 1;
}
2016-10-29 20:50:23.733144 Quiz for HoN[2741:902025] [FYB Debug]: Limit Ad Tracking: Disabled
2016-10-29 20:50:24.400352 Quiz for HoN[2741:902025] [ Heyzap ] Requesting initial credentials from server failed: retrying in 20 seconds. If this problem persists, contact support@heyzap.com.
2016-10-29 20:50:45.104822 Quiz for HoN[2741:902025] [ Heyzap ] Requesting initial credentials from server failed: retrying in 60 seconds. If this problem persists, contact support@heyzap.com.
```

I call my code when device is ready, cordova has been loaded, and after 20 seconds to make sure everything is ready. But nothing is working correctly, as I've been presented with white screen:

"Fyber Version 8.5.3 - Waiting for SDK to start"

**Comment by vintage** [comment]
I have same issue when calling `HeyzapAds.BannerAd.show`. So basically any function which should show ads doesn't work. Here are some info about my platform:

```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v6.4.0
Xcode version: Xcode 8.1 Build version 8B62
```

I've also tried to install plugin in both ways:
`cordova plugin add heyzap-cordova`
`cordova plugin add https://github.com/Heyzap/heyzap-cordova.git`

Same problem.

**Comment by MaxGabriel** [comment]
Hi, can you tell me the bundle identifier you're using for your app?

**Comment by vintage** [comment]
Hi, here you go: `com.puppybox.quizhon`. Currently I'm testing this library locally by deploying project from xcode to my iPhone/simulator.

**Comment by MaxGabriel** [comment]
Hey @vintage, could you fill out payment details on this page: https://developers.heyzap.com/account/payout_information?developer=puppybox

Sorry for the bad error message: When launched our SDK 10 hits our server to tell it to sync the game between Heyzap and Fyber, but the syncing process fails if payout information isn't added

**Comment by vintage** [comment]
@MaxGabriel: Thanks for the info. I've uploaded w9 / w8ben Form, submitted my paypal account, and provided billing address. Checked the app again, but same problem occurs. Do I have to wait for some approval from the Heyzap side?

**Comment by MaxGabriel** [comment]
Hey @vintage, should be working now!

**Comment by vintage** [comment]
Thanks @MaxGabriel it works now! :)

**Comment by jcstranger** [comment]
hey @MaxGabriel, i am having exactly the same problem. i submitted payment details yesterday but the console is still waiting for the SDK to start. is this just a matter of time (till payment method is approved) or is there anything else i am missing?

**Comment by zoreslavs** [comment]
Hi there,
I have the same issue - "Waiting for SDK to start". Even after fulfilled all the payment details.

**Comment by jcstranger** [comment]
anything?

**Comment by algenepulido** [comment]
same problem here... any quick fixes? else, need to check other ad mediation services
